name: RouterOS 7.x Download Workflow

on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      host:
        required: true
        type: string
      override_cache:
        default: false
        required: false
        type: boolean
      prefix:
        required: true
        type: string
      ref:
        required: true
        type: string
      reuse_commits:
        default: true
        required: false
        type: boolean
      reuse_releases:
        default: true
        required: false
        type: boolean
      tag:
        required: true
        type: string
      version:
        required: true
        type: string

permissions:
  actions: write
  contents: write

jobs:
  download:
    runs-on: ubuntu-24.04
    steps:
      - name: Look up downloaded files in cache
        id: lookup_cache
        uses: actions/cache/restore@v4
        with:
          key: "${{ inputs.ref }}-download"
          lookup-only: true
          path: 'sandbox'

      - name: Generate download URLs
        id: generate_urls
        if: ${{ inputs.override_cache || steps.lookup_cache.outputs.cache-hit != 'true' }}
        run: |
          BRANCH="${{ inputs.ref }}"
          TAG="${{ inputs.tag }}"
          echo "self_r=https://github.com/${{ github.repository }}/releases/download/${TAG}" >> $GITHUB_OUTPUT
          echo "self_c=https://github.com/${{ github.repository }}/raw/refs/heads/${BRANCH}" >> $GITHUB_OUTPUT
          echo "vendor=https://${{ inputs.host }}/routeros/${{ inputs.version }}" >> $GITHUB_OUTPUT

      - name: Download files from release, branch or vendor
        id: download_files
        if: ${{ inputs.override_cache || steps.lookup_cache.outputs.cache-hit != 'true' }}
        run: |
          sudo app/download.sh -d 'sandbox' -l "${{ inputs.prefix }}" -v "${{ inputs.version }}"

      - name: Delete downloaded files from cache
        id: delete_cache
        if: ${{ inputs.override_cache && steps.lookup_cache.outputs.cache-hit == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/caches?key=${{ inputs.ref }}-download&ref=${{ github.ref }}

      - name: Save downloaded files from 'sandbox' directory to cache
        id: save_cache
        if: ${{ inputs.override_cache || steps.lookup_cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          key: "${{ inputs.ref }}-download"
          path: 'sandbox'
